# Generated by Django 4.2.7 on 2025-04-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_player_position_alter_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstat',
            name='date',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='stats',
        ),
        migrations.AddField(
            model_name='playerstat',
            name='at_bats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='game_date',
            field=models.DateField(default='2025-04-07'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerstat',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='home_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='rbis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='strikeouts',
            field=models.IntegerField(default=0),
        ),
    ]
