# Generated by Django 4.2.7 on 2025-03-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_team_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='full_name',
        ),
    ]
