# Generated by Django 4.2.7 on 2025-04-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_pitchingstat_earned_runs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstat',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sport'),
        ),
        migrations.AlterField(
            model_name='pitchingstat',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.team'),
        ),
    ]
