# Generated by Django 4.2.7 on 2025-04-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_playerstat_date_remove_playerstat_stats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstat',
            name='at_bats',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='strikeouts',
        ),
        migrations.AddField(
            model_name='playerstat',
            name='doubles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='hit_by_pitch',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='stolen_bases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='triples',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='walks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='home_runs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='rbis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='runs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
