# Generated by Django 4.2.7 on 2025-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_pitchingstat_sport_alter_pitchingstat_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='strikeouts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
