# Generated by Django 4.2.7 on 2025-04-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_playerstat_at_bats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='at_bats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
