# Generated by Django 4.2.7 on 2025-04-07 03:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_playerstat_at_bats'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField(default=django.utils.timezone.now)),
                ('innings_pitched', models.DecimalField(decimal_places=1, max_digits=4)),
                ('hits_allowed', models.PositiveIntegerField(default=0)),
                ('runs_allowed', models.PositiveIntegerField(default=0)),
                ('earned_runs', models.PositiveIntegerField(default=0)),
                ('walks', models.PositiveIntegerField(default=0)),
                ('strikeouts', models.PositiveIntegerField(default=0)),
                ('home_runs_allowed', models.PositiveIntegerField(default=0)),
                ('pitches_thrown', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sport')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.team')),
            ],
        ),
    ]
